version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - ./code:/code
            - /code/api/vendor # ignore folder
        networks:
            - web-network
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        environment:
            - MYSQL_HOST
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
            - ./code:/code
            - /code/api/vendor # ignore folder
        networks:
            - web-network
            - app-network
        depends_on:
            - mysql

    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - "33080:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./docker/mysql/migrations:/docker-entrypoint-initdb.d
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
            - ./docker/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - app-network

    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        environment:
            - NODE_ENV
        volumes:
            - ./code:/code
            - /code/frontend/node_modules # ignore folder
        networks:
            - web-network

networks:
    web-network:
    app-network:
